Collapse to default: take out package and import from JUnit tests.
JUnit tests now all run. One exception caused by reading contacts.txt:

(default package) (1)
RetrieveContactsDotTxtTest
testContactManagerFrom_Test_ContactsDotTxt(RetrieveContactsDotTxtTest)
java.lang.RuntimeException: Error in decodingXML string to an Object.
Details: com.thoughtworks.xstream.mapper.CannotResolveClassException:
contactmanager.ContactManagerImpl
	at ...