test dodgy input produces exceptions... initially fails because have not yet coded this. Trace:
MeetingImplTest
SupplyNullArgumentsToConstructor(MeetingImplTest)
java.lang.AssertionError: Expected exception:
java.lang.NullPointerException
	at ... 

SupplyEmptyContactsToConstructor(MeetingImplTest)
java.lang.AssertionError: Expected exception:
java.lang.IllegalArgumentException
	at ...