Turns out my idea of casting a futureMeeting to a ... past meeting was a poor one - it is now allowed to downcast:
PastMeetingImplTest
castFutureMeetingToPastAddNotes(PastMeetingImplTest)
java.lang.ClassCastException: FutureMeetingImpl cannot be cast to
PastMeetingImpl
	at ...

So instead will need a constructor for PastMeeting that takes an
existing ID to be able to create a new PastMeeting that has information
from a future one.