aveStateToFileName() JUnit test adapted... from method with the same name in FileSaveRetrieveTest
Currently fails because of stub implementation of
saveToFile in SerialEncoderImpl, Trace:

SerialEncoder_Test
serialencodertest.SerialEncoder_Test
[0]
saveStateToFileName[0](serialencodertest.SerialEncoder_Test)
java.lang.RuntimeException: not yet implemented
	at
serialencoder.SerialEncoderImpl.saveToFile(SerialEncoderImpl.java:53)
	at ...
[1]
saveStateToFileName[1](serialencodertest.SerialEncoder_Test)
java.lang.RuntimeException: not yet implemented
	at
serialencoder.SerialEncoderImpl.saveToFile(SerialEncoderImpl.java:53)
	at ...