Refactoring #2 clean up time. Alter JUnit tests to work again using the timetools. see https://github.com/BBK-PiJ-2014-66/cw4/wiki/Refactoring-%232-clean-up-time
All tests run fine except:
uk.fictitiousurl.contactmanagertest

uk.fictitiousurl.contactmanagertest.RetrieveContactsDotTxtTest
testContactManagerFrom_Test_ContactsDotTxt(uk.fictitiousurl.contactmanagertest.RetrieveContactsDotTxtTest)
java.lang.RuntimeException: Error in decodingXML string to an Object.
Details: com.thoughtworks.xstream.mapper.CannotResolveClassException:
contactmanager.ContactManagerImpl
	at ...
	
Problems is the change in the package namespace means old contacts.txt
cannot be read