catch denormalization of contact ... coded up but the JUnit still needs to be fixed:
ContactManagerImplTest
test.ContactManagerImplTest
testaddFutureMeetingClonedContact(test.ContactManagerImplTest)
java.lang.AssertionError: 
Providing a cloned contact for a future meeting correctly produced a
RuntimeException,
but its message failed to contain 'clone'. Message is:
java.lang.IllegalArgumentException: Cloned contact: name='Test Name',
notes='Test Contact Notes', id=54 (this is forbidden).
	at ...