FileSaveRetrieve interface... finish off by using Interface rather than Impl when using it in ContactManagerImpl.
Unit test for ContactManagerImpl fails because the contacts.txt
and contacts.xml files need updating to reflect new Class
structure. (xstream exception messages are nice)

Trace:

ContactManagerImplTest
test.ContactManagerImplTest
testContactManagerFrom_Test_ContactsDotTxt(test.ContactManagerImplTest)
java.lang.RuntimeException: Error in deserialization of string to
contactManager. Details: java.io.InvalidClassException:
cw4.ContactManagerImpl; local class incompatible: stream classdesc
serialVersionUID = 1, local class serialVersionUID = 2
	at ...
	
testContactManagerFrom_Test_ContactsDotXML(test.ContactManagerImplTest)
java.lang.RuntimeException: Error in decodingXML string to
contactManager. Details:
com.thoughtworks.xstream.converters.ConversionException: Cannot
construct cw4.FileSaveRetrieve : cw4.FileSaveRetrieve : Cannot construct
cw4.FileSaveRetrieve : cw4.FileSaveRetrieve
---- Debugging information ----
message             : Cannot construct cw4.FileSaveRetrieve :
cw4.FileSaveRetrieve
cause-exception     :
com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Cannot construct cw4.FileSaveRetrieve :
cw4.FileSaveRetrieve
class               : cw4.FileSaveRetrieve
required-type       : cw4.FileSaveRetrieve
converter-type      :
com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /cw4.ContactManagerImpl/fileSR
line number         : 2
class[1]            : cw4.ContactManagerImpl
version             : 1.4.8
-------------------------------
	at ...