write fromXMLString() restore method.
Restores something but as ContactManagerImpl does not provide a decent
.equals the test fails:

	FileSaveRetrieveTest:
	testSaveToXmlStringAndRestore(FileSaveRetrieveTest)
	java.lang.AssertionError: Restored ContactManager equals original
	Expected: is <ContactManagerImpl@646d64ab>
     but: was <ContactManagerImpl@3d921e20>
	at....
	
Next step implement .equals in ContactManagerImpl!