addNewPastMeeting() test missing ... IllegalArgumentException for date in the future.
Fails because no check yet

ContactManagerImplTest
test.ContactManagerImplTest
addNewPastMeetingFutureDate(test.ContactManagerImplTest)
java.lang.AssertionError: Expected exception:
java.lang.IllegalArgumentException
	at ...