addNewPastMeeting() with unknown contact fails to produce required exception:
ContactManagerImplTest
test.ContactManagerImplTest
addNewPastMeetingUnknownContact(test.ContactManagerImplTest)
java.lang.AssertionError: Expected exception:
java.lang.IllegalArgumentException
	at ...