Test addFutureMeeting() with an unknown contact... that has not been added with addNewContact so is "unknown/non-existent". Interface requires this to produce an IllegalArgumentException.
Have not yet implemented the feature so unit test 
fails as it should. Trace:

	test.ContactManagerImplTest
	testaddFutureMeetingUnknownContact(test.ContactManagerImplTest)
	java.lang.AssertionError: Expected exception:
	java.lang.IllegalArgumentException
		at ...