refactor fileIO: implement saveToFile using serialEncoder. Development version using XSTREAMXML passes test. But still need to retrieve from file:
FileSaveRetrieveTest
test.FileSaveRetrieveTest
retrieveStateFromFileName(test.FileSaveRetrieveTest)
java.lang.RuntimeException: retriveToFile() needs new implementation
	at
cw4.FileSaveRetrieveImpl.retrieveFromFile(FileSaveRetrieveImpl.java:92)
	at ...