test getFutureMeeting(id) with past id ... this is required to produce exception but does not yet do so. Trace:
ContactManagerImplTest
test.ContactManagerImplTest
testGetFutureMeeting_PastID(test.ContactManagerImplTest)
java.lang.AssertionError: Expected exception:
java.lang.IllegalArgumentException
	at ..