refactor fileIO: test JOSBASE64 with hard coded switch for the "production". Need to make SerialEncoderImplJOSBASE64 serializable as it now a class variable!
FileSaveRetrieveTest
test.FileSaveRetrieveTest
retrieveStateFromFileName(test.FileSaveRetrieveTest)
java.lang.RuntimeException: Error in JOSBASE64 serialization of Object
to a String. Details: java.io.NotSerializableException:
serialencoder.SerialEncoderImplJOSBASE64
	at ...