SERIALIZATION: coded up encoding but get an exception:
FileSaveRetrieveTest
test.FileSaveRetrieveTest
saveToStringAndRestore(test.FileSaveRetrieveTest)
java.lang.RuntimeException: 
Error in serialization of contactManager to a String:
java.io.NotSerializableException: cw4.ContactManagerImpl
	at ...
	
Conclude need to make ContactManager Serializable (and its class
variable objects?)