refactor file IO: FileSaveRetrieveTest. Take out the save/retrieve to string tests as this functionality has been deleted. Take out parameterized test of XML and SERIALIZED - now save to one hard coded format only.
Tests compiles, runs and fails because of "stub" method

FileSaveRetrieveTest
test.FileSaveRetrieveTest
retrieveStateFromFileName(test.FileSaveRetrieveTest)
java.lang.RuntimeException: saveToFile() needs new implementation
	at cw4.FileSaveRetrieveImpl.saveToFile(FileSaveRetrieveImpl.java:57)
	at ...
	
saveStateToFileName(test.FileSaveRetrieveTest)
java.lang.RuntimeException: saveToFile() needs new implementation
	at cw4.FileSaveRetrieveImpl.saveToFile(FileSaveRetrieveImpl.java:57)
	at ...