First "stub" version. JUnit ContactImplTest... fails everytest as it should with the trace:
	ContactImplTest
	testGetBackNotes(ContactImplTest)
	java.lang.AssertionError: Use ContactImpl constructor name & notes, check that .getNotes() returns the supplied notes.
	Expected: is "email: joe.bloggs@fictious.com"
	     but: was null

	testTwoContactsHaveDistinctIDs(ContactImplTest)
	java.lang.AssertionError: ID of two contacts should be different.
	Expected: not <0>
	     but: was <0>

	testGetBackName(ContactImplTest)
	java.lang.AssertionError: Use ContactImpl constructor with just a name, check that getName returns the same.
	Expected: is "Joe Bloggs"
	     but: was null

	testAddNotes(ContactImplTest)
	java.lang.AssertionError: Supply notes with .addNotes & check that .getNotes() returns the supplied.
	Expected: is "email: joe.bloggs@fictious.com"
	     but: was null

	testGetBackId(ContactImplTest)
	java.lang.AssertionError: ContactImpl constructor with ID, check that .getID() returns the supplied ID.
	Expected: is <57>
	     but: was <0>