flush() implementation ... need to keep the FileSaveRetrieve as a class variable of ContactManagerImpl. So ContactManagerImpl alters and this means that FileSaveRetrieveTest fails for SERIALIZATION but not for XML (serialization is a pain!)
Trace: [0] XML passes, [1] SERIALIZATION fails with
       java.io.NotSerializableException: cw4.FileSaveRetrieve
       Errors -  So fix this.


FileSaveRetrieveTest
test.FileSaveRetrieveTest
[1]
attemptRestoreFromTruncatedString[1](test.FileSaveRetrieveTest)
java.lang.AssertionError: Attempt to restore ContactManager from
truncated string
Failure of test that exception message contains 'string to
contactManager'
Exception message is:
 java.lang.RuntimeException: Error in serialization of contactManager to
a String. Details: java.io.NotSerializableException:
cw4.FileSaveRetrieve
	at ...
	
retrieveStateFromFileName[1](test.FileSaveRetrieveTest)
java.lang.RuntimeException: Error in serialization of contactManager to
a String. Details: java.io.NotSerializableException:
cw4.FileSaveRetrieve
	at  ...

saveToStringAndRestore[1](test.FileSaveRetrieveTest)
java.lang.RuntimeException: Error in serialization of contactManager to
a String. Details: java.io.NotSerializableException:
cw4.FileSaveRetrieve
	at ...