test addMeetingNotes with meeting in the ... future. Unit test fails because have not yet implemented procedure to throw the required exception.
ContactManagerImplTest
test.ContactManagerImplTest
testAddMeetingWithMeetingInTheFuture(test.ContactManagerImplTest)
java.lang.AssertionError: Expected exception:
java.lang.IllegalArgumentException
	at ...