testaddFutureMeetingWithPastDate checks that an IllegalArgumentException is thrown when addFutureMeeting() is provided a old date.
Fails because feature not yet implemented with trace:
ContactManagerImplTest
ContactManagerImplTest
testaddFutureMeetingWithPastDate(ContactManagerImplTest)
java.lang.AssertionError: Expected exception:
java.lang.IllegalArgumentException
	at ...