Stub implementation fails both JUnit tests... as it should:
PastMeetingImplTest
testConstructAndGetters(PastMeetingImplTest)
java.lang.AssertionError: Get back the same notes as provided to
constructor?
Expected: is "Test notes"
     but: was null
	at ...
	
SupplyNullNotesToConstructor(PastMeetingImplTest)
java.lang.AssertionError: Expected exception:
java.lang.NullPointerException
	at ...