Refactor fileIO: ContactManagerImplTest take out XML specific tests as there is no switch save state.
Test fails because contacts.txt is not XML

ContactManagerImplTest
test.ContactManagerImplTest
testContactManagerFrom_Test_ContactsDotTxt(test.ContactManagerImplTest)
java.lang.RuntimeException: Error in decodingXML string to an Object.
Details: com.thoughtworks.xstream.io.StreamException:  : ParseError at
[row,col]:[1,1]
Message: Content is not allowed in prolog.
	at ...