Comment out package test and the imports to collapse everything into default.
Unit tests now run.

Get two failures because of the change to packages

(default package)
ContactManagerImplTest
testContactManagerFrom_Test_ContactsDotTxt(ContactManagerImplTest)
java.lang.RuntimeException: Error in deserialization of string to
contactManager. Details: java.lang.ClassNotFoundException:
cw4.ContactManagerImpl
	at ...
	
testContactManagerFrom_Test_ContactsDotXML(ContactManagerImplTest)
java.lang.RuntimeException: Error in decodingXML string to
contactManager. Details:
com.thoughtworks.xstream.mapper.CannotResolveClassException:
cw4.ContactManagerImpl
	at ...