Check that truncating string before decoding... produces an exception
Check what the exception is: for XML get more info?

debug truncate exception:
 java.lang.RuntimeException: Error in decodingXML string to
contactManager. Details:
com.thoughtworks.xstream.converters.ConversionException:  : ParseError
at [row,col]:[2,719]
Message: XML document structures must start and end within the same
entity. :  : ParseError at [row,col]:[2,719]
Message: XML document structures must start and end within the same
entity.
---- Debugging information ----
message             :  : ParseError at [row,col]:[2,719]
Message: XML document structures must start and end within the same
entity.
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       :  : ParseError at [row,col]:[2,719]
Message: XML document structures must start and end within the same
entity.
class               : java.util.GregorianCalendar
required-type       : java.util.GregorianCalendar
converter-type      :
com.thoughtworks.xstream.converters.extended.GregorianCalendarConverter
path                :
/cw4.ContactManagerImpl/futureMeetings/cw4.FutureMeetingImpl[3]/date/timezone
line number         : 2
class[1]            : cw4.FutureMeetingImpl
converter-type[1]   :
com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : java.util.ArrayList
converter-type[2]   :
com.thoughtworks.xstream.converters.collections.CollectionConverter
class[3]            : cw4.ContactManagerImpl
version             : 1.4.8
-------------------------------
debug truncate exception:
 java.lang.RuntimeException: Error in deserialization of string to
contactManager. Details: java.io.EOFException